"""initial schema

Revision ID: 12df5acb614a
Revises:
Create Date: 2026-02-19 14:25:00.226805

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "12df5acb614a"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kvk_number", sa.String(length=20), nullable=True),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("normalized_name", sa.String(length=500), nullable=False),
        sa.Column("sbi_codes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("employee_range", sa.String(length=50), nullable=True),
        sa.Column("revenue_range", sa.String(length=50), nullable=True),
        sa.Column("entity_count", sa.Integer(), nullable=True),
        sa.Column(
            "enrichment_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("enriched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_companies_kvk_number"), "companies", ["kvk_number"], unique=True
    )
    op.create_index(
        op.f("ix_companies_normalized_name"),
        "companies",
        ["normalized_name"],
        unique=False,
    )
    op.create_table(
        "search_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_search_profiles_slug"), "search_profiles", ["slug"], unique=True
    )
    op.create_table(
        "harvest_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("vacancies_found", sa.Integer(), nullable=False),
        sa.Column("vacancies_new", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["profile_id"], ["search_profiles.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "search_terms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("term", sa.String(length=500), nullable=False),
        sa.Column("language", sa.String(length=10), nullable=False),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"], ["search_profiles.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "vacancies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.String(length=500), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("search_profile_id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.Column("company_name_raw", sa.String(length=500), nullable=False),
        sa.Column("job_title", sa.String(length=500), nullable=False),
        sa.Column("job_url", sa.String(length=2000), nullable=True),
        sa.Column("location", sa.String(length=500), nullable=True),
        sa.Column("raw_text", sa.Text(), nullable=True),
        sa.Column(
            "extracted_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("harvest_run_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["harvest_run_id"], ["harvest_runs.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["search_profile_id"], ["search_profiles.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_vacancy_company_profile",
        "vacancies",
        ["company_id", "search_profile_id"],
        unique=False,
    )
    op.create_index(
        "ix_vacancy_source_external",
        "vacancies",
        ["source", "external_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_vacancy_source_external", table_name="vacancies")
    op.drop_index("ix_vacancy_company_profile", table_name="vacancies")
    op.drop_table("vacancies")
    op.drop_table("search_terms")
    op.drop_table("harvest_runs")
    op.drop_index(op.f("ix_search_profiles_slug"), table_name="search_profiles")
    op.drop_table("search_profiles")
    op.drop_index(op.f("ix_companies_normalized_name"), table_name="companies")
    op.drop_index(op.f("ix_companies_kvk_number"), table_name="companies")
    op.drop_table("companies")
    # ### end Alembic commands ###
