"""add enrichment models and tracking fields

Revision ID: d63e5a581591
Revises: 12df5acb614a
Create Date: 2026-02-19 15:12:29.805588

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d63e5a581591"
down_revision: Union[str, Sequence[str], None] = "12df5acb614a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "enrichment_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("pass_type", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("items_processed", sa.Integer(), nullable=False),
        sa.Column("items_succeeded", sa.Integer(), nullable=False),
        sa.Column("items_failed", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("tokens_input", sa.Integer(), nullable=False),
        sa.Column("tokens_output", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"], ["search_profiles.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "extraction_prompts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("system_prompt", sa.Text(), nullable=False),
        sa.Column(
            "extraction_schema", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["profile_id"], ["search_profiles.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "companies",
        sa.Column(
            "enrichment_status",
            sa.String(length=20),
            nullable=False,
            server_default="pending",
        ),
    )
    op.add_column(
        "companies", sa.Column("enrichment_run_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "companies",
        sa.Column("kvk_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "companies",
        sa.Column(
            "company_info_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "companies", sa.Column("extraction_quality", sa.Float(), nullable=True)
    )
    op.create_foreign_key(
        None,
        "companies",
        "enrichment_runs",
        ["enrichment_run_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "vacancies",
        sa.Column(
            "extraction_status",
            sa.String(length=20),
            nullable=False,
            server_default="pending",
        ),
    )
    op.add_column(
        "vacancies", sa.Column("extraction_run_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None,
        "vacancies",
        "enrichment_runs",
        ["extraction_run_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "vacancies", type_="foreignkey")
    op.drop_column("vacancies", "extraction_run_id")
    op.drop_column("vacancies", "extraction_status")
    op.drop_constraint(None, "companies", type_="foreignkey")
    op.drop_column("companies", "extraction_quality")
    op.drop_column("companies", "company_info_data")
    op.drop_column("companies", "kvk_data")
    op.drop_column("companies", "enrichment_run_id")
    op.drop_column("companies", "enrichment_status")
    op.drop_table("extraction_prompts")
    op.drop_table("enrichment_runs")
    # ### end Alembic commands ###
